export const PLAYNOTE = 'PLAYNOTE';
export const PLAYNUMBER = 'PLAYNUMBER';
export const NEWPAPER = 'NEWPAPER';
export const NEWPATCH = 'NEWPATCH';
export const CREATESYNTH = 'CREATESYNTH';
export const TRIGGERATTACK = 'TRIGGERATTACK';
export const TRIGGERRELEASE = 'TRIGGERRELEASE';
export const TRIGGERATTACKRELEASE = 'TRIGGERATTACKRELEASE';
export const ENVELOPE = 'ENVELOPE';
export const PARAM = 'PARAM';


//transport actions
export const TRANSPORTSTART             = 'TRANSPORTSTART'
export const TRANSPORTSTOP              = 'TRANSPORTSTOP';
export const TRANSPORTSCHEDULE          = 'TRANSPORTSCHEDULE';
export const TRANSPORTSCHEDULEREPEAT    = 'TRANSPORTSCHEDULEREPEAT';
export const TRANSPORTSCHEDULEONCE      = 'TRANSPORTSCHEDULEONCE';
export const TRANSPORTBPM               = 'TRANSPORTBPM';
